//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCard
    {
        public int Id { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
